# Generated by Django 2.2.1 on 2019-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_auto_20190813_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='ABC', max_length=10, unique=True),
        ),
    ]
