# Generated by Django 2.2.1 on 2019-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_auto_20190813_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=True, related_name='Sharer', to='joins.Join')),
                ('emailall', models.ForeignKey(on_delete=True, related_name='emailall', to='joins.Join')),
                ('friends', models.ManyToManyField(blank=True, null=True, related_name='Friend', to='joins.Join')),
            ],
        ),
    ]
