# Generated by Django 2.2.1 on 2019-08-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_joinfriends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinFriends',
        ),
    ]
