# Generated by Django 2.2.1 on 2019-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0008_delete_joinfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='referral', to='joins.Join'),
        ),
    ]
